version: 0.2

env:
  variables:
    REPOSITORY_NAME: spring-app-2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - "REPOSITORY_URI=400054515716.dkr.ecr.us-east-1.amazonaws.com/spring-app-2"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - "IMAGE_TAG=build-$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Maven project..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing imagedefinitions.json for ECS..."
      - printf '[{"name":"spring-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json 
      - echo "Build completed successfully."

artifacts:
  files:
    - imagedefinitions.json
